terraform {
  required_version = ">= 1.9.0"

  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.43"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Managed PostgreSQL 18.
#
# Managed, not self-operated — docs/09 §4.1 is explicit: "we do not operate
# PostgreSQL by hand at MVP." Backups, PITR and failover are the parts that
# matter and the parts a small team gets wrong under pressure.
#
# ⚠️ PostGIS and TimescaleDB are BOTH required and are not optional extras:
# `driver_positions` is a hypertable and every address carries a geography
# column. A cluster without them fails at migration 0007, not at runtime.
# ─────────────────────────────────────────────────────────────────────────────
resource "digitalocean_database_cluster" "postgres" {
  name    = "${var.project}-${var.environment}-pg"
  engine  = "pg"
  version = "18"
  region  = var.region

  size = var.postgres_size
  # 2 nodes is a standby, not a read replica — automatic failover. Tier 2 adds
  # genuine read replicas for analytics (docs/06 §7).
  node_count = var.postgres_node_count

  # ⚠️ Private only. A managed database with a public endpoint is one leaked
  # credential away from a cross-tenant dump, and Row-Level Security does not
  # constrain `dp_migrator`, which owns the schema.
  private_network_uuid = var.vpc_id

  maintenance_window {
    # 02:00 UTC Tuesday: 03:00 in Tunis, the quietest hour for a courier, and
    # midweek so a failed maintenance has working days either side of it.
    day  = "tuesday"
    hour = "02:00:00"
  }
}

resource "digitalocean_database_db" "app" {
  cluster_id = digitalocean_database_cluster.postgres.id
  name       = var.database_name
}

# ─────────────────────────────────────────────────────────────────────────────
# The three least-privilege identities (CLAUDE.md, initdb/02-roles.sql).
#
# ⚠️ THIS SEPARATION IS WHAT MAKES RLS REAL.
#
#   dp_app      — what the application connects as. NO BYPASSRLS, no DDL.
#   dp_migrator — owns the schema. Runs migrations, never serves a request.
#   dp_relay    — cross-tenant on `outbox` only, for the publication relay.
#
# Pointing any two at the same identity silently disables tenant isolation: the
# app role would hold the migrator's privileges, and FORCE ROW LEVEL SECURITY
# does not restrain a role that can simply ALTER the policy away. The config
# schema refuses to boot if the URLs match, but the roles have to exist
# separately for that check to mean anything.
#
# Passwords are generated by DigitalOcean and never appear in a `.tf` file. They
# land in state, which is why state lives in a private remote backend.
# ─────────────────────────────────────────────────────────────────────────────
resource "digitalocean_database_user" "app" {
  cluster_id = digitalocean_database_cluster.postgres.id
  name       = "dp_app"
}

resource "digitalocean_database_user" "migrator" {
  cluster_id = digitalocean_database_cluster.postgres.id
  name       = "dp_migrator"
}

resource "digitalocean_database_user" "relay" {
  cluster_id = digitalocean_database_cluster.postgres.id
  name       = "dp_relay"
}

# ─────────────────────────────────────────────────────────────────────────────
# Managed Valkey.
#
# Persistence enabled (docs/09 §4.1). Valkey holds more than a cache here:
# driver presence with a 90-second TTL — where EXPIRY IS THE OFFLINE SIGNAL —
# the event streams the outbox relay publishes to, and consumer-group state. A
# flush loses the position of every consumer group, and at-least-once delivery
# becomes at-most-once.
# ─────────────────────────────────────────────────────────────────────────────
resource "digitalocean_database_cluster" "valkey" {
  name       = "${var.project}-${var.environment}-valkey"
  engine     = "valkey"
  version    = "8"
  region     = var.region
  size       = var.valkey_size
  node_count = var.valkey_node_count

  private_network_uuid = var.vpc_id

  maintenance_window {
    day  = "tuesday"
    hour = "03:00:00"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Firewall: only the application droplets may reach either cluster.
#
# Belt and braces with the private network. The VPC already excludes the public
# internet; this excludes anything else the account happens to own in the same
# VPC — a staging droplet, a colleague's experiment.
# ─────────────────────────────────────────────────────────────────────────────
resource "digitalocean_database_firewall" "postgres" {
  cluster_id = digitalocean_database_cluster.postgres.id

  dynamic "rule" {
    for_each = var.allowed_droplet_tags
    content {
      type  = "tag"
      value = rule.value
    }
  }
}

resource "digitalocean_database_firewall" "valkey" {
  cluster_id = digitalocean_database_cluster.valkey.id

  dynamic "rule" {
    for_each = var.allowed_droplet_tags
    content {
      type  = "tag"
      value = rule.value
    }
  }
}
